(()=>{
const thresholds={electricity:100,internet:80,mobile:60,other:80};
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const typeName=t=>({electricity:'كهرباء',internet:'إنترنت',mobile:'موبايل',other:'أخرى'})[t]||t;
function thresholdFor(c){return thresholds[c?.type]??80}
function offersFor(c){return state.offers.filter(o=>o.contractId===c.id).sort((a,b)=>(b.saving||0)-(a.saving||0))}
function recommendation(c){const offers=offersFor(c),best=offers[0],threshold=thresholdFor(c),current=annual(c);if(!current)return{level:'warning',decision:'أكمل بيانات التكلفة',detail:'لا يمكن إصدار توصية مالية قبل معرفة التكلفة السنوية الحالية.',best:null};if(!offers.length)return{level:'warning',decision:'ابحث عن عروض',detail:`أي عرض يوفر أكثر من ${money(threshold)} سنوياً يستحق التغيير المبدئي.`,best:null};if(best.saving>=threshold)return{level:'good',decision:'✓ التغيير موصى به',detail:`أفضل عرض يوفر ${money(best.saving)} سنوياً، وهو أعلى من حد القرار ${money(threshold)}.`,best};if(best.saving>0)return{level:'warning',decision:'ابقَ حالياً',detail:`أفضل عرض يوفر ${money(best.saving)} فقط؛ أقل من حد القرار ${money(threshold)}.`,best};return{level:'danger',decision:'ابقَ مع عقدك الحالي',detail:'العروض المسجلة أغلى من عقدك الحالي أو لا تحقق أي توفير.',best}}
function renderAdvisor(){const offersPanel=document.querySelector('#offers');if(!offersPanel)return;let box=document.querySelector('#advisorSummary');if(!box){box=document.createElement('div');box.id='advisorSummary';offersPanel.insertBefore(box,document.querySelector('#offerArea'))}if(!state.contracts.length){box.innerHTML='';return}box.innerHTML=state.contracts.map(c=>{const r=recommendation(c),best=r.best;return `<article class="card advisorCard"><div class="cardTop"><div><span class="badge ${r.level}">${r.decision}</span><h3>${c.provider}</h3><div class="muted">${typeName(c.type)}${c.tariff?' · '+c.tariff:''}</div></div><div class="price">${annual(c)?money(annual(c)):'—'}<small class="muted">/سنة</small></div></div><p>${r.detail}</p>${best?`<div class="meta"><div>أفضل بديل<br><b>${best.provider}</b></div><div>تكلفة البديل<br><b>${money(best.newAnnual)}</b></div><div>التوفير<br><b>${money(best.saving)}</b></div><div>حد القرار<br><b>${money(thresholdFor(c))}</b></div></div>`:''}</article>`}).join('')}
function addTools(){let main=document.querySelector('main');if(!main||document.querySelector('#dataTools'))return;let tools=document.createElement('section');tools.id='dataTools';tools.className='dataTools';tools.innerHTML=`<details><summary>النسخة الاحتياطية والخصوصية</summary><div class="card"><p class="muted">بيانات العقود محفوظة على جهازك. أنشئ Backup دوري حتى لا تضيع عند حذف بيانات المتصفح.</p><div class="cardActions"><button id="exportBackup" class="secondary">تنزيل Backup</button><button id="importBackupBtn" class="secondary">استعادة Backup</button><input id="importBackupFile" type="file" accept="application/json" hidden></div></div></details>`;main.appendChild(tools);document.querySelector('#exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`contract-saver-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};document.querySelector('#importBackupBtn').onclick=()=>document.querySelector('#importBackupFile').click();document.querySelector('#importBackupFile').onchange=async e=>{try{const f=e.target.files?.[0];if(!f)return;const j=JSON.parse(await f.text()),d=j.data||j;if(!Array.isArray(d.contracts)||!Array.isArray(d.offers)||!Array.isArray(d.savings))throw new Error('ملف غير صالح');if(confirm('سيتم استبدال البيانات الحالية بالنسخة الاحتياطية. متابعة؟')){state=d;save();renderAdvisor()}}catch(err){alert('تعذر استعادة النسخة الاحتياطية: '+err.message)}}}
const originalRender=window.render;let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;renderAdvisor()})});
window.addEventListener('load',()=>{addTools();renderAdvisor();const a=document.querySelector('#offerArea');if(a)observer.observe(a,{childList:true,subtree:true})});
setTimeout(()=>{addTools();renderAdvisor()},300);
window.contractSaverAdvisor={recommendation,thresholds};
})();