(()=>{
const $=s=>document.querySelector(s),dlg=$('#importDialog'),fileInput=$('#contractFile'),analyzeBtn=$('#analyzeBtn'),aiAnalyzeBtn=$('#aiAnalyzeBtn'),progress=$('#importProgress'),progressBar=$('#progressBar'),progressText=$('#progressText'),err=$('#importError'),fileName=$('#importFileName');
let currentFile=null,lastText='';
const setProgress=(p,t)=>{progress.hidden=false;progressBar.style.width=Math.max(2,Math.min(100,p))+'%';progressText.textContent=t};
const showError=m=>{err.hidden=false;err.textContent=m;progress.hidden=true};
const reset=()=>{currentFile=null;lastText='';fileInput.value='';fileName.textContent='';err.hidden=true;progress.hidden=true;progressBar.style.width='0%';analyzeBtn.disabled=true;aiAnalyzeBtn.disabled=true};
$('#importBtn').onclick=()=>{reset();dlg.showModal()};$('#closeImport').onclick=()=>dlg.close();
fileInput.onchange=()=>{currentFile=fileInput.files?.[0]||null;lastText='';fileName.textContent=currentFile?`${currentFile.name} · ${(currentFile.size/1024/1024).toFixed(2)} MB`:'';analyzeBtn.disabled=!currentFile;aiAnalyzeBtn.disabled=!currentFile;err.hidden=true};
function clean(s){return(s||'').replace(/\u00ad/g,'').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').trim()}
function dateISO(v){if(!v)return'';let m=v.match(/(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})/);if(m){let y=+m[3];if(y<100)y+=2000;return`${y}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`}m=v.match(/(20\d{2})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}-${String(+m[2]).padStart(2,'0')}-${String(+m[3]).padStart(2,'0')}`:''}
function num(v){if(!v)return 0;let s=String(v).replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.').replace(/[^\d.]/g,'');let n=parseFloat(s);return Number.isFinite(n)?n:0}
function first(text,res){for(const re of res){let m=text.match(re);if(m)return m[1]||m[0]}return''}
function near(text,words,re,limit=280){let low=text.toLowerCase();for(const w of words){let i=low.indexOf(w.toLowerCase());if(i>=0){let m=text.slice(Math.max(0,i-40),i+limit).match(re);if(m)return m[1]||m[0]}}return''}
function preferred(text){let low=text.toLowerCase();for(const a of['ihre neuen vertragsdaten nach der tarifänderung','ihre neuen vertragsdaten','ihr neuer ökostrom-tarif ab','neue vertragsdaten']){let i=low.indexOf(a);if(i>=0)return text.slice(i,Math.min(text.length,i+2400))}return text.slice(0,Math.min(text.length,7000))}
function extract(text){text=clean(text);let low=text.toLowerCase(),type='other';if(/strom|elektrizit|kwh|arbeitspreis|ökostrom/.test(low))type='electricity';else if(/internet|dsl|glasfaser|mbit/.test(low))type='internet';else if(/mobilfunk|sim.?karte|datenvolumen|5g|lte/.test(low))type='mobile';let section=preferred(text);let provider=(first(text,[/\b(eprimo)\s+gmbh\b/i,/\b(vodafone)\s+(?:gmbh|deutschland)/i,/\b(deutsche telekom|telekom)\b/i,/\b(e\.on|eon)\b/i,/\b(vattenfall)\b/i,/\b(enbw)\b/i,/\b(o2)\b/i,/\b(1&1)\b/i,/\b(octopus energy)\b/i,/\b(tibber)\b/i,/\b(maingau)\b/i])||'').trim();let tariff=first(section,[/(?:ökostrom[- ]tarif|stromtarif|tarifname|tarif|produktname|produkt)\s*:\s*([^\n]{2,80})/i])||first(text,[/ihr neuer ökostrom[- ]tarif\s*:\s*([^\n]{2,80})/i]);tariff=(tariff||'').replace(/\s+(preisgarantie|vertragslaufzeit|kündigung).*$/i,'').trim();let start=type==='electricity'?dateISO(first(text,[/ihr neuer ökostrom[- ]tarif ab\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i,/ab dem\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})\s+beliefern wir sie/i])):'';let end=dateISO(first(section,[/vertragslaufzeit\s*:\s*bis(?: zum)?\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i,/vertragslaufzeit bis(?: zum)?\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i]));let cancel=dateISO(first(section,[/nächstmöglicher kündigungstermin\s*:\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i]));let bonus=num(first(section,[/(?:bonus(?: für ihre treue)?|neukundenbonus|sofortbonus|cashback)\s*:\s*(\d{1,5}(?:[.,]\d{1,2})?)\s*(?:€|eur)/i])||near(text,['bonus für ihre treue','neukundenbonus','sofortbonus','bonus'],/(\d{1,5}(?:[.,]\d{1,2})?)\s*(?:€|eur)/i));let monthly=0,workPrice=0,basePrice=0,annualUsage=0,monthlyPayment=0;if(type==='electricity'){workPrice=num(first(section,[/ab\s*\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2}\s+(\d{1,3}(?:[.,]\d{1,3})?)\s*ct\/kwh/i,/arbeitspreis(?:\s+ht)?\s*[:\-]?\s*(\d{1,3}(?:[.,]\d{1,3})?)\s*ct\/kwh/i]));basePrice=num(first(section,[/ab\s*\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2}[^\n]{0,100}?(\d{1,4}(?:[.,]\d{1,2})?)\s*€\/monat/i,/grundpreis\s*[:\-]?\s*(\d{1,4}(?:[.,]\d{1,2})?)\s*€\/?monat/i]));monthlyPayment=num(first(section,[/(?:monatlicher abschlag|abschlag pro monat|abschlagszahlung)\s*[:\-]?\s*(\d{1,4}(?:[.,]\d{1,2})?)\s*(?:€|eur)/i]));annualUsage=num(first(text,[/(?:jahresverbrauch|prognoseverbrauch|verbrauchsprognose|voraussichtlicher jahresverbrauch)\s*[:\-]?\s*([\d.]+)\s*kwh/i]));}else monthly=num(first(section,[/(?:monatlicher grundpreis|monatlicher preis|grundgebühr|monatlich)\s*[:\-]?\s*(\d{1,4}(?:[.,]\d{1,2})?)\s*(?:€|eur)/i]));let vals=[type!=='other',provider,tariff,start,end,cancel,bonus,type==='electricity'?(workPrice&&basePrice):monthly];let confidence=Math.round(vals.filter(Boolean).length/vals.length*100);return{type,provider,tariff,monthly,workPrice,basePrice,annualUsage,monthlyPayment,bonus,start,end,cancel,confidence}}
async function pdfText(file){if(!window.pdfjsLib)throw new Error('PDF reader unavailable');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';let data=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,out='',pages=Math.min(pdf.numPages,12);for(let i=1;i<=pages;i++){setProgress(10+Math.round((i/pages)*45),`قراءة صفحة ${i} من ${pages}…`);let p=await pdf.getPage(i),tc=await p.getTextContent();out+='\n'+tc.items.map(x=>x.str).join(' ')}if(out.replace(/\s/g,'').length>120)return out;let ocr='';pages=Math.min(pdf.numPages,3);for(let i=1;i<=pages;i++){let p=await pdf.getPage(i),vp=p.getViewport({scale:1.7}),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=vp.width;canvas.height=vp.height;await p.render({canvasContext:ctx,viewport:vp}).promise;ocr+='\n'+await ocrImage(canvas,i,pages)}return ocr}
async function ocrImage(image,page=1,total=1){if(!window.Tesseract)throw new Error('OCR engine unavailable');let r=await Tesseract.recognize(image,'deu+eng',{logger:m=>{if(m.status==='recognizing text')setProgress(60+Math.round((m.progress||0)*32),`OCR ${total>1?`صفحة ${page}/${total}`:'للصورة'}: ${Math.round((m.progress||0)*100)}%`)}});return r.data.text||''}
async function getText(){if(lastText)return lastText;if(!currentFile)throw new Error('اختر ملفاً أولاً.');lastText=currentFile.type==='application/pdf'||currentFile.name.toLowerCase().endsWith('.pdf')?await pdfText(currentFile):await ocrImage(currentFile);return lastText}
function fill(d,source='local'){ $('#contractForm').reset();$('#editId').value='';for(const k of['type','provider','tariff','monthly','workPrice','basePrice','annualUsage','monthlyPayment','start','cancel','end','bonus']){let el=$('#'+k);if(el)el.value=d[k]||''}$('#bonus').value=d.bonus||0;let notes=source==='ai'?`تحليل AI — الثقة: ${d.confidence||0}%.\n${d.summary||''}`:`تم الاستيراد تلقائياً. دقة أولية: ${d.confidence||0}%. راجع القيم قبل الحفظ.`;if(d.cancelNotice)notes+=`\nKündigungsfrist: ${d.cancelNotice}`;if(d.priceGuarantee)notes+=`\nPreisgarantie: ${d.priceGuarantee}`;if(Array.isArray(d.warnings)&&d.warnings.length)notes+=`\nتنبيهات: ${d.warnings.join(' | ')}`;$('#notes').value=notes;$('#formTitle').textContent=source==='ai'?`راجع تحليل AI (${d.confidence||0}%)`:`راجع البيانات المستخرجة (${d.confidence||0}%)`;if(typeof syncType==='function')syncType();dlg.close();$('#contractDialog').showModal()}
analyzeBtn.onclick=async()=>{if(!currentFile)return;analyzeBtn.disabled=true;aiAnalyzeBtn.disabled=true;err.hidden=true;try{setProgress(4,'بدء التحليل المحلي…');let text=await getText();setProgress(95,'استخراج بيانات العقد…');let d=extract(text);if(!d.provider&&!d.tariff&&!d.start&&!d.end&&!d.cancel)throw new Error('لم أتمكن من استخراج بيانات موثوقة.');setProgress(100,'تم الاستخراج.');setTimeout(()=>fill(d,'local'),250)}catch(e){showError(e?.message||'حدث خطأ أثناء التحليل.')}finally{analyzeBtn.disabled=false;aiAnalyzeBtn.disabled=false}};
aiAnalyzeBtn.onclick=async()=>{if(!currentFile)return;analyzeBtn.disabled=true;aiAnalyzeBtn.disabled=true;err.hidden=true;try{setProgress(4,'قراءة العقد قبل إرسال النص إلى AI…');let text=await getText();setProgress(65,'AI يحلل شروط العقد…');let token=localStorage.getItem('contractSaver.aiToken')||'';let headers={'Content-Type':'application/json'};if(token)headers['X-App-Token']=token;let r=await fetch('/api/analyze-contract',{method:'POST',headers,body:JSON.stringify({text})});if(r.status===401){let entered=prompt('أدخل رمز الوصول الخاص بالـAI Backend. سيُحفظ على هذا الجهاز فقط.');if(!entered)throw new Error('يلزم رمز الوصول لتشغيل AI.');localStorage.setItem('contractSaver.aiToken',entered);headers['X-App-Token']=entered;r=await fetch('/api/analyze-contract',{method:'POST',headers,body:JSON.stringify({text})})}let d=await r.json().catch(()=>({}));if(!r.ok){if(location.hostname.includes('github.io'))throw new Error('زر AI جاهز، لكن يجب فتح نسخة Vercel من التطبيق لأن GitHub Pages لا يشغّل الـBackend.');throw new Error(d.error||'فشل تحليل AI.')}setProgress(100,'اكتمل تحليل AI.');setTimeout(()=>fill(d,'ai'),250)}catch(e){showError(e?.message||'حدث خطأ أثناء تحليل AI.')}finally{analyzeBtn.disabled=false;aiAnalyzeBtn.disabled=false}};
})();