(()=>{
const monthlyWords=/monatlich\s+k[uü]ndbar|monatlich\s+k[uü]ndigen|jederzeit\s+k[uü]ndbar|jederzeit\s+mit\s+.{0,30}k[uü]ndigungsfrist|zum\s+monatsende\s+k[uü]ndbar|unbefristet.{0,80}k[uü]nd/i;
function isMonthly(c){return c?.cancelMode==='monthly'}
function syncCancellationMode(){const mode=document.querySelector('#cancelMode')?.value||'fixed',fixed=document.querySelector('#fixedCancelFields');if(fixed)fixed.style.display=mode==='monthly'?'none':'block';const hint=document.querySelector('#monthlyCancelHint');if(hint)hint.style.display=mode==='monthly'?'block':'none'}
window.syncCancellationMode=syncCancellationMode;
const mode=document.querySelector('#cancelMode');if(mode)mode.addEventListener('change',syncCancellationMode);
const oldReview=review;review=function(c){if(isMonthly(c))return['شهرياً قابل للإلغاء','badge good'];return oldReview(c)};
const oldTaskFor=taskFor;taskFor=function(c){if(isMonthly(c))return{level:'good',title:'يمكنك التغيير في أي وقت',detail:`هذا العقد قابل للإلغاء شهرياً${c.cancelNotice?` (${c.cancelNotice})`:''}. قارن العروض متى ظهر بديل أوفر.`};return oldTaskFor(c)};
const form=document.querySelector('#contractForm'),oldSubmit=form?.onsubmit;if(form&&oldSubmit){form.onsubmit=e=>{const modeVal=document.querySelector('#cancelMode')?.value||'fixed',notice=document.querySelector('#cancelNotice')?.value.trim()||'';const editId=document.querySelector('#editId')?.value||'';oldSubmit.call(form,e);let c=editId?state.contracts.find(x=>x.id===editId):state.contracts[state.contracts.length-1];if(c){c.cancelMode=modeVal;c.cancelNotice=notice;if(modeVal==='monthly')c.cancel='';localStorage.setItem(KEY,JSON.stringify(state));render();if(window.contractSaverAdvisor?.refresh)window.contractSaverAdvisor.refresh()}}}
const oldAdd=document.querySelector('#addBtn')?.onclick;if(oldAdd)document.querySelector('#addBtn').onclick=()=>{oldAdd();if(document.querySelector('#cancelMode'))document.querySelector('#cancelMode').value='fixed';if(document.querySelector('#cancelNotice'))document.querySelector('#cancelNotice').value='';syncCancellationMode()};
const oldEdit=window.editContract;window.editContract=id=>{oldEdit(id);const c=state.contracts.find(x=>x.id===id);if(document.querySelector('#cancelMode'))document.querySelector('#cancelMode').value=c?.cancelMode||'fixed';if(document.querySelector('#cancelNotice'))document.querySelector('#cancelNotice').value=c?.cancelNotice||'';syncCancellationMode()};
const dlg=document.querySelector('#contractDialog');if(dlg){new MutationObserver(()=>{if(!dlg.open)return;const notes=document.querySelector('#notes')?.value||'';if(monthlyWords.test(notes)&&document.querySelector('#cancelMode')?.value!=='monthly'){document.querySelector('#cancelMode').value='monthly';const m=notes.match(/Kündigungsfrist:\s*([^\n]+)/i);if(m&&document.querySelector('#cancelNotice'))document.querySelector('#cancelNotice').value=m[1].trim();syncCancellationMode()}}).observe(dlg,{attributes:true,attributeFilter:['open']})}
state.contracts.forEach(c=>{if(!c.cancelMode)c.cancelMode='fixed';if(!c.cancelNotice)c.cancelNotice=''});localStorage.setItem(KEY,JSON.stringify(state));syncCancellationMode();render();
window.contractSaverLifecycle={isMonthly,syncCancellationMode};
})();