(()=>{
const $=s=>document.querySelector(s);let generatorPromise=null;const MODEL='onnx-community/SmolLM2-135M-Instruct-ONNX';
function setProgress(p,t){const box=$('#importProgress'),bar=$('#progressBar'),txt=$('#progressText');if(box)box.hidden=false;if(bar)bar.style.width=Math.max(2,Math.min(100,p))+'%';if(txt)txt.textContent=t}
function showError(m){const e=$('#importError');if(e){e.hidden=false;e.textContent=m}}
function clean(s){return String(s||'').replace(/\u00ad/g,'').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').trim()}
function num(v){if(!v)return 0;let s=String(v).replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.').replace(/[^\d.]/g,'');let n=parseFloat(s);return Number.isFinite(n)?n:0}
function dateISO(v){if(!v)return'';let m=String(v).match(/(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})/);if(m){let y=+m[3];if(y<100)y+=2000;return`${y}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`}return''}
function first(text,res){for(const re of res){let m=text.match(re);if(m)return m[1]||m[0]}return''}
function preferred(text){let low=text.toLowerCase();for(const a of['ihre neuen vertragsdaten nach der tarifänderung','ihre neuen vertragsdaten','ihr neuer ökostrom-tarif ab','neue vertragsdaten']){let i=low.indexOf(a);if(i>=0)return text.slice(i,Math.min(text.length,i+2600))}return text.slice(0,Math.min(text.length,8000))}
function extract(text){text=clean(text);let low=text.toLowerCase(),type='other';if(/strom|elektrizit|kwh|arbeitspreis|ökostrom/.test(low))type='electricity';else if(/internet|dsl|glasfaser|mbit/.test(low))type='internet';else if(/mobilfunk|sim.?karte|datenvolumen|5g|lte/.test(low))type='mobile';const section=preferred(text);let provider=(first(text,[/\b(eprimo)\s+gmbh\b/i,/\b(vodafone)\s+(?:gmbh|deutschland)/i,/\b(deutsche telekom|telekom)\b/i,/\b(e\.on|eon)\b/i,/\b(vattenfall)\b/i,/\b(enbw)\b/i,/\b(o2)\b/i,/\b(1&1)\b/i,/\b(octopus energy)\b/i,/\b(tibber)\b/i,/\b(maingau)\b/i])||'').trim();let tariff=first(section,[/(?:ökostrom[- ]tarif|stromtarif|tarifname|tarif|produktname|produkt)\s*:\s*([^\n]{2,80})/i])||first(text,[/ihr neuer ökostrom[- ]tarif\s*:\s*([^\n]{2,80})/i]);tariff=(tariff||'').replace(/\s+(preisgarantie|vertragslaufzeit|kündigung).*$/i,'').trim();let start=type==='electricity'?dateISO(first(text,[/ihr neuer ökostrom[- ]tarif ab\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i,/ab dem\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})\s+beliefern wir sie/i])):'';let end=dateISO(first(section,[/vertragslaufzeit\s*:\s*bis(?: zum)?\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i,/vertragslaufzeit bis(?: zum)?\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i]));let cancel=dateISO(first(section,[/nächstmöglicher kündigungstermin\s*:\s*(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})/i]));let bonus=num(first(section,[/(?:bonus(?: für ihre treue)?|neukundenbonus|sofortbonus|cashback)\s*:\s*(\d{1,5}(?:[.,]\d{1,2})?)\s*(?:€|eur)/i]));let cancelNotice=first(section,[/kündigungsfrist\s*:\s*([^\n]{1,40})/i]).trim();let priceGuarantee=first(section,[/preisgarantie\s*:\s*([^\n]{1,40})/i]).trim();let monthly=0,workPrice=0,basePrice=0,annualUsage=0,monthlyPayment=0;if(type==='electricity'){workPrice=num(first(section,[/ab\s*\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2}\s+(\d{1,3}(?:[.,]\d{1,3})?)\s*ct\/kwh/i,/arbeitspreis(?:\s+ht)?\s*[:\-]?\s*(\d{1,3}(?:[.,]\d{1,3})?)\s*ct\/kwh/i]));basePrice=num(first(section,[/ab\s*\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2}[^\n]{0,120}?(\d{1,4}(?:[.,]\d{1,2})?)\s*€\/monat/i,/grundpreis\s*[:\-]?\s*(\d{1,4}(?:[.,]\d{1,2})?)\s*€\/?monat/i]));monthlyPayment=num(first(section,[/(?:monatlicher abschlag|abschlag pro monat|abschlagszahlung)\s*[:\-]?\s*(\d{1,4}(?:[.,]\d{1,2})?)\s*(?:€|eur)/i]));annualUsage=num(first(text,[/(?:jahresverbrauch|prognoseverbrauch|verbrauchsprognose|voraussichtlicher jahresverbrauch)\s*[:\-]?\s*([\d.]+)\s*kwh/i]));}else monthly=num(first(section,[/(?:monatlicher grundpreis|monatlicher preis|grundgebühr|monatlich)\s*[:\-]?\s*(\d{1,4}(?:[.,]\d{1,2})?)\s*(?:€|eur)/i]));let vals=[type!=='other',provider,tariff,start,end,cancel,type==='electricity'?(workPrice&&basePrice):monthly];let confidence=Math.round(vals.filter(Boolean).length/vals.length*100);return{type,provider,tariff,monthly,workPrice,basePrice,annualUsage,monthlyPayment,start,end,cancel,cancelNotice,bonus,priceGuarantee,confidence}}
async function ocrImage(image){if(!window.Tesseract)throw new Error('OCR غير متاح');let r=await Tesseract.recognize(image,'deu+eng',{logger:m=>{if(m.status==='recognizing text')setProgress(25+Math.round((m.progress||0)*30),`OCR: ${Math.round((m.progress||0)*100)}%`)}});return r.data.text||''}
async function readFile(file){if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){if(!window.pdfjsLib)throw new Error('قارئ PDF غير متاح');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';let pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,out='',pages=Math.min(pdf.numPages,12);for(let i=1;i<=pages;i++){setProgress(8+Math.round((i/pages)*42),`قراءة صفحة ${i}/${pages}…`);let p=await pdf.getPage(i),tc=await p.getTextContent();out+='\n'+tc.items.map(x=>x.str).join(' ')}if(out.replace(/\s/g,'').length>120)return out;let p=await pdf.getPage(1),vp=p.getViewport({scale:1.7}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;return ocrImage(c)}return ocrImage(file)}
function fallbackSummary(d){const p=[];if(d.provider)p.push(`Anbieter: ${d.provider}`);if(d.tariff)p.push(`Tarif: ${d.tariff}`);if(d.type==='electricity'){if(d.workPrice)p.push(`Arbeitspreis ${d.workPrice} ct/kWh`);if(d.basePrice)p.push(`Grundpreis ${d.basePrice} €/Monat`)}if(d.cancel)p.push(`Kündigungstermin ${d.cancel}`);if(d.end)p.push(`Vertragsende ${d.end}`);if(d.bonus)p.push(`Bonus ${d.bonus} €`);return p.join(' · ')}
async function loadGenerator(){if(generatorPromise)return generatorPromise;generatorPromise=(async()=>{setProgress(60,'تحميل AI مفتوح المصدر على جهازك لأول مرة…');const mod=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.3');const hasGPU=!!navigator.gpu;return mod.pipeline('text-generation',MODEL,{dtype:hasGPU?'q4f16':'q8',device:hasGPU?'webgpu':'wasm',progress_callback:x=>{if(x?.status==='progress'&&Number.isFinite(x.progress))setProgress(60+Math.round(x.progress*.22),`تحميل AI المحلي: ${Math.round(x.progress)}%`)}})})();return generatorPromise}
async function localAI(text,base){let summary=fallbackSummary(base),warnings=[];try{const g=await loadGenerator();setProgress(84,'AI المحلي يحلل العقد بدون إرسال بياناتك للخارج…');const context=preferred(clean(text)).slice(0,6500);const prompt=`You are a German contract assistant. Use only the text. Give a concise German summary in max 4 sentences. Prefer new/future tariff data over old data. Mention cancellation, price guarantee, bonus and important price terms when present. Do not invent facts.\nKnown facts: ${JSON.stringify(base)}\nContract: ${context}\nSummary:`;let out=await g(prompt,{max_new_tokens:140,do_sample:false,repetition_penalty:1.08}),gen=out?.[0]?.generated_text;if(Array.isArray(gen))gen=gen[gen.length-1]?.content||'';gen=String(gen||'');if(gen.includes('Summary:'))gen=gen.split('Summary:').pop().trim();if(gen.length>20)summary=gen.slice(0,1200)}catch(e){console.warn(e);warnings.push('تعذر تشغيل النموذج اللغوي على هذا الجهاز؛ تم استخدام الاستخراج الذكي المحلي المجاني كبديل.')}return{...base,summary,warnings,confidence:Math.max(base.confidence||0,80)}}
function fill(d){for(const k of['type','provider','tariff','monthly','workPrice','basePrice','annualUsage','monthlyPayment','start','cancel','end','bonus']){let el=$('#'+k);if(el)el.value=d[k]||''}if($('#bonus'))$('#bonus').value=d.bonus||0;let n=`تحليل AI محلي مجاني — الثقة: ${d.confidence||0}%.\n${d.summary||''}`;if(d.cancelNotice)n+=`\nKündigungsfrist: ${d.cancelNotice}`;if(d.priceGuarantee)n+=`\nPreisgarantie: ${d.priceGuarantee}`;if(d.warnings?.length)n+=`\nتنبيهات: ${d.warnings.join(' | ')}`;$('#notes').value=n;$('#formTitle').textContent=`راجع التحليل المحلي (${d.confidence||0}%)`;if(typeof syncType==='function')syncType();$('#importDialog').close();$('#contractDialog').showModal()}
const btn=$('#aiAnalyzeBtn');if(btn){btn.textContent='✦ AI محلي مجاني';btn.onclick=async()=>{const file=$('#contractFile')?.files?.[0];if(!file)return;btn.disabled=true;$('#analyzeBtn').disabled=true;$('#importError').hidden=true;try{setProgress(4,'بدء التحليل المجاني على جهازك…');const text=await readFile(file);const base=extract(text);setProgress(55,'تم استخراج البيانات، تشغيل AI المحلي…');const result=await localAI(text,base);setProgress(100,'اكتمل التحليل المجاني.');setTimeout(()=>fill(result),200)}catch(e){showError(e?.message||'تعذر التحليل المحلي.')}finally{btn.disabled=false;$('#analyzeBtn').disabled=false}}}
window.contractSaverLocalAI={model:MODEL};
const advisor=document.createElement('script');advisor.src='./advisor.js?v=10';advisor.defer=true;document.head.appendChild(advisor);
})();