(()=>{
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function addDays(date,delta){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+delta);return d}
function ymd(d){return d.toISOString().slice(0,10).replace(/-/g,'')}
function icsDate(d){return ymd(d)}
function downloadICS(c){let events=[];if(c.cancelMode==='monthly'){let d=new Date();d.setDate(1);d.setMonth(d.getMonth()+1);events.push({date:d,title:`مراجعة عقد ${c.provider} والبحث عن عرض أفضل`,desc:`العقد قابل للإلغاء شهرياً${c.cancelNotice?` (${c.cancelNotice})`:''}. افتح Contract Saver وقارن عروض السوق.`,rrule:'RRULE:FREQ=MONTHLY;INTERVAL=1'});}else if(c.cancel){[['بدء البحث عن عروض أفضل',-120],['مقارنة السوق',-90],['اختيار أفضل 3 عروض',-60],['قرار الإلغاء/التغيير',-30]].forEach(([t,delta])=>{let d=addDays(c.cancel,delta);if(d>=new Date(new Date().toDateString()))events.push({date:d,title:`${t}: ${c.provider}`,desc:`Contract Saver — Kündigungstermin: ${c.cancel}. ${c.tariff||''}`})});if(!events.length)events.push({date:new Date(),title:`راجع عقد ${c.provider} الآن`,desc:`موعد الإلغاء المسجل ${c.cancel} يحتاج مراجعة.`});}else{let d=new Date();d.setDate(d.getDate()+30);events.push({date:d,title:`مراجعة عقد ${c.provider}`,desc:'موعد الإلغاء غير مسجل. راجع العقد وابحث عن بدائل.'})}
const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');let txt=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Contract Saver Germany//AR','CALSCALE:GREGORIAN'];events.forEach((e,i)=>{txt.push('BEGIN:VEVENT',`UID:${c.id}-${i}@contract-saver`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${icsDate(e.date)}`,`SUMMARY:${e.title.replace(/,/g,'\\,')}`,`DESCRIPTION:${e.desc.replace(/\n/g,'\\n').replace(/,/g,'\\,')}`,e.rrule||'','BEGIN:VALARM','TRIGGER:-P1D','ACTION:DISPLAY','DESCRIPTION:Contract Saver reminder','END:VALARM','END:VEVENT')});txt.push('END:VCALENDAR');const blob=new Blob([txt.filter(Boolean).join('\r\n')],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`contract-saver-${(c.provider||'contract').replace(/[^a-z0-9_-]/gi,'_')}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function switchStatus(c){if(c.cancelMode==='monthly')return{cls:'good',text:`يمكن التغيير الآن؛ راعِ فقط مهلة ${c.cancelNotice||'الإلغاء الشهرية'}.`};if(!c.cancel)return{cls:'warning',text:'لا يمكن تأكيد إمكانية التغيير الآن لأن Kündigungstermin غير مسجل.'};let n=days(c.cancel);if(n<0)return{cls:'danger',text:'موعد الإلغاء المسجل انتهى؛ تحقق من وضع العقد الحالي أولاً.'};if(n<=120)return{cls:'good',text:`أنت داخل نافذة التخطيط للتغيير. بقي ${n} يوم حتى الموعد المسجل.`};return{cls:'warning',text:`العقد ليس في نافذة التغيير بعد. يبدأ البحث المنظم قبل 120 يوماً من ${c.cancel}.`}}
function profileFor(c){let p={};if(c.type==='electricity'){p.plz=prompt('أدخل PLZ لمكان استهلاك الكهرباء (يُستخدم للبحث فقط):',localStorage.getItem('contractSaver.plz')||'')||'';if(p.plz)localStorage.setItem('contractSaver.plz',p.plz);p.annualUsage=c.annualUsage||0}else if(c.type==='internet'){p.plz=prompt('أدخل PLZ للعنوان:',localStorage.getItem('contractSaver.plz')||'')||'';if(p.plz)localStorage.setItem('contractSaver.plz',p.plz);p.speed=+(prompt('السرعة المطلوبة Mbit/s:',localStorage.getItem('contractSaver.speed')||'100')||100);localStorage.setItem('contractSaver.speed',p.speed)}else if(c.type==='mobile'){p.dataGB=+(prompt('كم GB تحتاج تقريباً بالشهر؟',localStorage.getItem('contractSaver.dataGB')||'20')||20);localStorage.setItem('contractSaver.dataGB',p.dataGB);p.network=prompt('الشبكة المفضلة إن وجدت: Telekom / Vodafone / O2 / أي شبكة',localStorage.getItem('contractSaver.network')||'أي شبكة')||'أي شبكة';localStorage.setItem('contractSaver.network',p.network)}return p}
function ensureDialog(){let d=document.querySelector('#marketDialog');if(d)return d;d=document.createElement('dialog');d.id='marketDialog';d.innerHTML='<div class="importPanel"><div class="sectionHead"><h2>بحث السوق المجاني</h2><button id="closeMarket" class="secondary">إغلاق</button></div><div id="marketStatus" class="muted"></div><div id="marketResults"></div></div>';document.body.appendChild(d);d.querySelector('#closeMarket').onclick=()=>d.close();return d}
async function searchMarket(id){const c=state.contracts.find(x=>x.id===id);if(!c)return;const dlg=ensureDialog(),status=dlg.querySelector('#marketStatus'),box=dlg.querySelector('#marketResults');dlg.showModal();status.textContent='جاري البحث في مصادر عامة مجانية…';box.innerHTML='';try{const profile=profileFor(c),r=await fetch('/api/market-search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contract:c,profile})}),data=await r.json();if(!r.ok)throw new Error(data.error||'فشل البحث');const current=annual(c),sw=switchStatus(c);let comparable=(data.results||[]).filter(x=>x.comparable&&x.annual>0).map(x=>({...x,saving:current?current-x.annual:0})).sort((a,b)=>b.saving-a.saving);status.innerHTML=`<span class="badge ${sw.cls}">${esc(sw.text)}</span><p class="muted">البحث: ${esc(data.query||'')}</p>`;let html='';if(comparable.length){html+='<h3>نتائج يمكن مقارنتها مبدئياً</h3>'+comparable.slice(0,6).map(x=>`<article class="card"><h3>${esc(x.provider||x.title)}</h3><div class="muted">${esc(x.snippet||'')}</div><div class="meta"><div>السعر الملتقط<br><b>${x.monthly?money(x.monthly)+'/شهر':money(x.annual)+'/سنة'}</b></div><div>مقابل عقدك<br><b>${x.saving>0?'توفير '+money(x.saving):'أغلى '+money(Math.abs(x.saving))}</b></div><div>الثقة<br><b>${x.confidence==='medium'?'متوسطة':'منخفضة'}</b></div></div><div class="cardActions"><a class="linkButton compare" target="_blank" rel="noopener" href="${esc(x.url)}">افتح العرض وتحقق</a>${x.saving>0?`<button onclick="window.contractSaverMarket.addCandidate('${id}',${JSON.stringify(x.provider||x.title).replace(/"/g,'&quot;')},${x.annual})">أضف للمقارنة</button>`:''}</div></article>`).join('')}else html+='<div class="card"><b>لم أجد سعراً شخصياً موثوقاً يمكن حسابه تلقائياً.</b><p class="muted">هذا طبيعي خصوصاً للكهرباء والإنترنت لأن السعر يعتمد على العنوان. استخدم روابط المقارنة أدناه؛ الـAgent لن يخترع سعراً غير مؤكد.</p></div>';
if((data.results||[]).length){html+='<h3>مرشحون من البحث العام</h3>'+data.results.filter(x=>!x.comparable).slice(0,5).map(x=>`<div class="card"><b>${esc(x.title)}</b><p class="muted">${esc(x.snippet||'')}</p><a class="linkButton secondary" target="_blank" rel="noopener" href="${esc(x.url)}">فتح المصدر</a></div>`).join('')}
if((data.trusted||[]).length)html+='<h3>مقارنات موثوقة لإكمال البحث</h3>'+data.trusted.map(x=>`<div class="card"><b>${esc(x.title)}</b><p class="muted">${esc(x.note||'')}</p><a class="linkButton compare" target="_blank" rel="noopener" href="${esc(x.url)}">فتح المقارنة</a></div>`).join('');box.innerHTML=html||'<div class="empty">لا توجد نتائج حالياً.</div>'}catch(e){status.textContent='';box.innerHTML=`<div class="importError">${esc(e.message||'تعذر البحث حالياً.')}</div>`}}
function addCandidate(id,provider,annualPrice){const c=state.contracts.find(x=>x.id===id);if(!c||!annualPrice)return;const exists=state.offers.some(o=>o.contractId===id&&o.provider===provider&&Math.abs(o.newAnnual-annualPrice)<.01);if(exists){alert('هذا العرض موجود بالفعل في المقارنة.');return}state.offers.push({id:crypto.randomUUID(),contractId:id,provider,newAnnual:+annualPrice,saving:annual(c)-annualPrice,recorded:false,source:'market-search'});save();alert('تمت إضافة المرشح إلى تبويب المقارنة. راجع السعر والشروط من المصدر قبل اتخاذ القرار.')}
function decorate(){const cards=[...document.querySelectorAll('#contractList > .card')];cards.forEach((card,i)=>{const c=state.contracts[i];if(!c)return;let actions=card.querySelector('.cardActions');if(!actions)return;if(!actions.querySelector('.marketSearchBtn')){let b=document.createElement('button');b.className='marketSearchBtn compare';b.textContent='🔍 ابحث عن عرض أفضل';b.onclick=()=>searchMarket(c.id);actions.prepend(b)}if(!actions.querySelector('.calendarBtn')){let b=document.createElement('button');b.className='calendarBtn secondary';b.textContent='📅 أضف للكالندر';b.onclick=()=>downloadICS(c);actions.appendChild(b)}})}
let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})});window.addEventListener('load',()=>{decorate();const l=document.querySelector('#contractList');if(l)obs.observe(l,{childList:true,subtree:true})});setTimeout(decorate,300);
window.contractSaverMarket={searchMarket,downloadICS,addCandidate};
})();