function strip(html=''){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&euro;|&#8364;/gi,'€').replace(/\s+/g,' ').trim()}
function euroNumber(s){if(!s)return 0;let x=String(s).replace(/\./g,'').replace(',','.').replace(/[^\d.]/g,'');let n=parseFloat(x);return Number.isFinite(n)?n:0}
function decodeDuck(url=''){try{let u=new URL(url,'https://duckduckgo.com');let uddg=u.searchParams.get('uddg');return uddg?decodeURIComponent(uddg):url}catch{return url}}
function parseDDG(html){const out=[];const re=/<a[^>]+class="result__a"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>[\s\S]{0,1800}?(?:class="result__snippet"[^>]*>([\s\S]*?)<\/a>|class="result__snippet"[^>]*>([\s\S]*?)<\/div>)/gi;let m;while((m=re.exec(html))&&out.length<12){const title=strip(m[2]),snippet=strip(m[3]||m[4]||''),url=decodeDuck(m[1]);if(title&&url)out.push({title,snippet,url})}return out}
function extractMonthly(text=''){let m=text.match(/(?:ab\s*)?(\d{1,3}(?:[.,]\d{1,2})?)\s*€\s*(?:\/\s*Monat|pro\s*Monat|monatlich)/i);return m?euroNumber(m[1]):0}
function extractAnnual(text=''){let m=text.match(/(?:Kosten\s*(?:im\s*ersten\s*Jahr|pro\s*Jahr)|Jahrespreis|jährlich)\s*[:\-]?\s*(\d{1,5}(?:[.,]\d{1,2})?)\s*(?:€|Euro)/i);return m?euroNumber(m[1]):0}
function extractGB(text=''){let m=text.match(/(\d{1,4})\s*GB\b/i);return m?+m[1]:0}
function providerFrom(title=''){return title.split(/[|–—-]/)[0].trim().slice(0,60)}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});try{const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),c=b.contract||{},p=b.profile||{};let query='';if(c.type==='mobile'){query=`monatlich kündbar Mobilfunktarif ${p.dataGB||''} GB ${p.network||''} 5G Deutschland Preis`;}
else if(c.type==='internet'){query=`Internettarif ${p.plz||''} ${p.speed||''} Mbit DSL Kabel Glasfaser Preis`;}
else if(c.type==='electricity'){query=`Stromtarif ${p.plz||''} ${c.annualUsage||p.annualUsage||''} kWh Arbeitspreis Grundpreis Deutschland`;}
else query=`${c.type||'Vertrag'} Tarif Deutschland Preis`;
const ddg=`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`;const r=await fetch(ddg,{headers:{'User-Agent':'Mozilla/5.0 ContractSaver/1.0'}});const html=await r.text();let results=parseDDG(html).map(x=>{const full=`${x.title} ${x.snippet}`,monthly=extractMonthly(full),annual=extractAnnual(full),gb=extractGB(full);let comparable=false,estimatedAnnual=0,confidence='lead';if(c.type==='mobile'||c.type==='internet'){if(monthly>0){estimatedAnnual=monthly*12;comparable=true;confidence='medium'}}else if(c.type==='electricity'&&annual>0){estimatedAnnual=annual;comparable=true;confidence='low'}return{...x,provider:providerFrom(x.title),monthly,annual:estimatedAnnual,dataGB:gb,comparable,confidence}}).filter(x=>x.url&&/^https?:/i.test(x.url));
const trusted={electricity:[{title:'Verivox Stromvergleich',url:'https://www.verivox.de/strompreisvergleich/',note:'PLZ und Jahresverbrauch eingeben'},{title:'CHECK24 Stromvergleich',url:'https://www.check24.de/strom/',note:'PLZ und Jahresverbrauch eingeben'}],mobile:[{title:'CHECK24 monatlich kündbare Handytarife',url:'https://handytarife.check24.de/lp/monats-tarife',note:'Flexible Tarife vergleichen'}],internet:[{title:'CHECK24 Internetvergleich',url:'https://www.check24.de/internet/internetanbieter/',note:'Adressbasierte Verfügbarkeit prüfen'},{title:'Verivox Internetvergleich',url:'https://www.verivox.de/internet/',note:'Tarife nach Adresse vergleichen'}]}[c.type]||[];
return res.status(200).json({query,results:results.slice(0,10),trusted,generatedAt:new Date().toISOString()});}catch(e){return res.status(500).json({error:e?.message||'Market search failed'})}}
